// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiCsio_rrjhw4URUOv9NLB0nEMzlSUURA',
    appId: '1:754051757048:web:5e806c3569a1918a511c0d',
    messagingSenderId: '754051757048',
    projectId: 'u-kar-abc9d',
    authDomain: 'u-kar-abc9d.firebaseapp.com',
    storageBucket: 'u-kar-abc9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChLH6Zn9477J6z3Cp8GJgpoeBdSvirITM',
    appId: '1:754051757048:android:229b8c907c453d81511c0d',
    messagingSenderId: '754051757048',
    projectId: 'u-kar-abc9d',
    storageBucket: 'softwaredev',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPSxWLmKfVpP-OEnAipzfRlV-IEXWJt4I',
    appId: '1:754051757048:ios:42f6044e62d31df1511c0d',
    messagingSenderId: '754051757048',
    projectId: 'u-kar-abc9d',
    storageBucket: 'u-kar-abc9d.appspot.com',
    iosBundleId: 'com.example.chatdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPSxWLmKfVpP-OEnAipzfRlV-IEXWJt4I',
    appId: '1:754051757048:ios:82dfa91ea76b43cf511c0d',
    messagingSenderId: '754051757048',
    projectId: 'u-kar-abc9d',
    storageBucket: 'u-kar-abc9d.appspot.com',
    iosBundleId: 'com.example.chatdemo.RunnerTests',
  );
}
